- .circleci/config.yml
- package.json
**Scope:** ci
*  Unit or Functional tests are included in the PR No
We want to make easier the release process, and delegate all the work in commons scripts and in a CI remove a lot of headaches and problems.
The new scripts layout are:
- Versioning:
- release - a simple release following Conventional Commits (`vX.Y.Z`)
- release:prerelease - with Conventional Commits it will determine next latest version and with Conventional Prerelease and preid it will create the prerelease (`vX.Y.Z-next.N`)
- release:from-prerelease - with Conventional Commits it will determine next latest version and with Conventional Graduate it will exit from prerelease cycle (`vX.Y.Z-next.N` -> `vX.Y.Z`)
- …
> chore: add the ability to prerelease in other dist tag

- tools/eslint-config/.editorconfig
- tools/eslint-config/index.js
- tools/eslint-config/package.json
- tools/eslint-config/rules/base.js
- tools/eslint-config/rules/import.js
- tools/eslint-config/rules/jest.js
- tools/eslint-config/rules/prettier.js
- tools/eslint-config/rules/typescript.js
**Scope:** eslint-config
*  There is a related issue? **No*
**Description:** separate in different files the rules with their own scope, so in a future we can maintain rules better. An example is if we need to improve Prettier settings, we can go to _rules/prettier.js_ instead of searching in a whole world of mixed rules
> refactor(eslint-config): refactor project structure to separate rules in categories

- .circleci/config.yml
- verdaccio.yml
**Type:** ci
**Scope:** ci
*  There is a related issue? **Part of #13**
**Description:** Use Verdaccio with some plugins to test in-memory publish before real publish. These steps will only run when we try to publish, but we can improve in a future trying to use in each compilation (emulate a publish).
> ci: publish pacakges to an in-memory registry to ensure publish works well

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
**Scope:** devcontainer
*  There is a related issue? **No**
**Description:** We have a simple configuration for VSCode Remote Development with the main things needed to develop in this repository. That configuration uses the main `node:latest` docker image, which size is 908MB after download.
In VSCode 1.38.0, the support for Alpine images has been included, so we can use it. The main difference is that `node:alpine` docker image doesn't include many tools we need, so we have to add them manually in a Dockerifle. The size of the base image is 80.3MB and, after installing those tools (git, bash, python, g++, make and dependencies), 289MB.
> chore: use Alpine image in DevContainers

- .github/workflows/ci.yml
**Type:** ci
**Scope:** Github Actions
*  Unit or Functional tests are included in the PR No
**Description:** In [actions/setup-actions@v1.1.1](https://github.com/actions/setup-node/releases/tag/v1.1.1), version was deprecated in favor of node_version. Also, rename job and file to ci (to demostrate its purpose).
> ci(github): improve naming and fix setup-node action

- core/types/index.d.ts
> fix: adds sort_packages in WebConf Interface

- core/types/index.d.ts
**Type:** bug
**Scope:** types
Add missing `allow_unpublish` generic interface
Add
```
type AuthAccessCallback = (error: string | null, access: boolean) => void;
type AuthCallback = (error: string | null, groups: string[] | false) => void;
```
The type `AuthAccessCallback` is intended to be more reliable in order to create plugins.
> fix: add allow_unpublish generic

- plugins/google-cloud/src/data-storage.ts
in getSecret, if /Secret does not exist, we had an async
error uncaught. Catch it explicitly so that the Secret
will get created.
**Type:**
**Scope:**
> fix(verdaccio-google-cloud): catch missing Secret on first run

- plugins/aws-s3-storage/README.md
- plugins/aws-s3-storage/src/index.ts
Recently a new feature was introduced to allow passing the configuration values through environment variables only this didn't cover the `endpoint`-config this PR adds supports for defining the S3 Endpoint in the environment variables.
> Allow endpoint to be configurable

- tools/babel-preset/lib/builder.js
**Type:**
issue fix
**Scope:**
fixes missing babel typescript plugins in the `test` environment like `proposal-optional-chaining` which would fail verdaccio unit test if the syntax is used.
> fix: resolve missing missing 'babel/proposal-optional-chaining' in test env

- core/readme/package.json
- yarn.lock
`@verdaccio/readme` uses `jsdom@15.x.x` and there is a security patch
https://app.snyk.io/test/npm/jsdom/15.2.1
> fix: security dependency jsdom@16.2.0 update

- plugins/local-storage/package.json
- plugins/local-storage/src/local-fs.ts
- yarn.lock
**Type:** security
**Scope:** local-storage
* update `mkdirp@1.0.3`
* fix create file, now returns a promise
> fix: update mkdirp@1.0.3

- plugins/htpasswd/src/crypt3.ts
- plugins/htpasswd/src/utils.ts
- plugins/htpasswd/tests/crypt3.test.ts
- plugins/htpasswd/tests/htpasswd.test.ts
- plugins/htpasswd/tests/utils.test.ts
**Type:** bug/feature
**Scope:** verdaccio-htpasswd
The crypt implementation in use does not actually support the newer hash types. Calling it with a prefixed salt results in the prefix becoming the salt and rendering the salt useless as it is now constant.
This PR adds an unprefixed salt type for legacy 2 byte salting and requests that by default.
I have not updated the snapshot tests as it seems not possible to provide a single fixed password string to test against. Mocking the salt generation as is done in the crypt3.ts tests would possibly work, but I am not familiar enough with the test framework to provide this right now.
> fix(verdaccio-htpasswd): generate non-constant legacy 2 byte salt

- core/readme/package.json
- plugins/local-storage/package.json
- plugins/local-storage/src/local-fs.ts
- yarn.lock
**Type:**  refactor
**Scope:** all
this downgrade to dependencies (to fixed ones) and restore v8 support removed in previous releases.
Restore `mkdirp` and `jsdom`.
Resolves #355
> fix: restore Node v8 support

- plugins/aws-s3-storage/README.md
- plugins/aws-s3-storage/src/config.ts
- plugins/aws-s3-storage/src/index.ts
- plugins/aws-s3-storage/src/s3PackageManager.ts
- plugins/aws-s3-storage/tests/setConfigValue.test.ts
**Type:Feature**
**Scope:aws-s3-storage**
Ability to provide session token when connecting to private s3 bucket.
*  There is a related issue? 
No.
*  Unit or Functional tests are not included in the PR
No, looked at the existing unit tests. This is only adding a value to the config and I don't see any tests checking each config value. Please advice if I need to add tests.
Sometimes session tokens are required to be able to connect. Adding the ability to add session token to config.
> feat: allow providing session token in config

- .changeset/curly-cherries-glow.md
- plugins/aws-s3-storage/src/s3PackageManager.ts
- plugins/aws-s3-storage/tests/s3PackageManagerMockedS3.test.ts
**Type: Bug
**Scope: plugins/aws-s3-storage
This PR resolves [this issue ](https://github.com/verdaccio/verdaccio/issues/1984). 
The PR add trailing slashes to the prefix of listobjects when removing a package. This is maded to not match more packages than it should.
> Fix the prefix used to delete from s3 when unpublishing packages

- plugins/google-cloud/README.md
**Type:** docs
**Scope:** verdaccio-google-cloud
*  Unit or Functional tests are included in the PR: No, docs only.
- clarify and link to info about Firestore modes
- improve config example
- fix out of date links
- fix typos
> docs(verdaccio-google-cloud): updates for GCP changes

- .changeset/config.json
- .changeset/happy-lies-pretend.md
- core/readme/src/index.ts
- core/readme/tests/readme.spec.ts
Added optional options object param to `parseReadme` where `{pathname: string}` can define the `pathname` to use when resolving anchor links by pre-padding the `pathname` to the anchor link.
Helps to resolve https://github.com/verdaccio/verdaccio/issues/2712
> feat: parseReadme pathname option

- .changeset/cold-files-drop.md
- plugins/memory/src/memory-handler.ts
- plugins/memory/test/memory.spec.ts
**Type:** bug
**Scope:** memory plugin
The memory plugin was not correctly writing tarballs that have the same name but are from different packages and have different content.
Backport of https://github.com/verdaccio/verdaccio/pull/3200
> fix: Fix storing same named files from different pkgs in memory plugin

- .changeset/tough-turtles-matter.md
- plugins/htpasswd/README.md
- plugins/htpasswd/package.json
- plugins/htpasswd/src/crypt3.ts
- plugins/htpasswd/src/htpasswd.ts
- plugins/htpasswd/src/index.ts
- plugins/htpasswd/src/utils.ts
- plugins/htpasswd/tests/__snapshots__/utils.test.ts.snap
- plugins/htpasswd/tests/crypt3.test.ts
- plugins/htpasswd/tests/htpasswd.test.ts
- plugins/htpasswd/tests/utils.test.ts
- pnpm-lock.yaml
> ⚠️  TLDR: Use bcrypt is much secure, verdaccio 5 uses `crypt` by default to avoid breakign changes, next major (v6) will switch to bcrypt by default and invalidate your current passwords. This does not apply if you are using your own authentication plugin. 
**Type:** feat
**Scope:** plugin
copied from v6 plugins by @greshilov https://github.com/verdaccio/verdaccio/pull/2072
> To avoid a breaking change, the default algorithm is `crypt`.
The current implementation of the `htpasswd` module supports multiple hash formats on verify, but only `crypt` on sign in.
`crypt` is an insecure old format, so to improve the security of the new `verdaccio` release …
> feat: allow other password hashing algorithms

- .changeset/plenty-donkeys-begin.md
- plugins/local-storage/src/token.ts
**Type:** fix
**Scope:** local-storage
This might be the issue some has been reported the packages are not found. Workaround was using absolute path.
Regression here https://github.com/verdaccio/monorepo/pull/394
> fix: regresion wrong new storage path reference

- plugins/aws-s3-storage/package.json
- pnpm-lock.yaml
Update of `aws-sdk` package inside plugin `verdaccio-aws-s3-storage`, in order to try to fix https://github.com/verdaccio/monorepo/issues/668
We did it locally and for now the crash didn't came back
> core: update package aws-sdk

- .changeset/eight-mangos-tickle.md
- plugins/active-directory/src/active-directory.ts
- Missing logging option https://www.npmjs.com/package/activedirectory2
- #702 fails here https://github.com/ldapjs/node-ldapjs/blob/master/lib/client/client.js#L873
Resolves #https://github.com/verdaccio/monorepo/issues/702
> fix: active directory missing logging option

- plugins/aws-s3-storage/README.md
**Type:** bug, documentation
**Scope:** verdaccio-aws-s3-storage
- Primarily a fix for the invalid capitalisation of the `accessKeyID` configuration key
- Also tidied up related documentation by removing duplication of important information (making it clearer), and adding formatting.
This was the cause (for me) of the misleading error in #695
> fix: typo in readme, clarify aws-s3-storage configuration

- plugins/aws-s3-storage/src/s3Errors.ts
**Type:** Bug
**Scope:** verdaccio-aws-s3-storage
* When an error occurs with the SDK outside of an HTTP request then the error's statusCode will be `undefined`, which will trigger a TypeError in common code outside the plugin, masking the true error (eg. missing AWS credentials)
This change sets a fallback 500 status code so that error handling will continue.
Resolves #695
> fix: handle s3 errors without a status code
