- .circleci/config.yml
- package.json
- yarn.lock
This is basically an upgrade of Lerna to use new commands like version and have the benefits of latest version (and not the current release candidate version we use).
> chore: modernize project

- README.md
- packages/eslint-config/LICENSE
- packages/eslint-config/README.md
- packages/eslint-config/index.js
- packages/eslint-config/package.json
- yarn.lock
**Related package:** @verdaccio/eslint-config
**Description**: Add a basic Eslint configuration that will grow when import other core projects to monorepo.
>  feat(eslint-config): add @verdaccio/eslint-config

- README.md
- azure-pipelines.yml
- core/commons-api/.prettierrc
- core/commons-api/package.json
- core/file-locking/.prettierrc
- core/file-locking/package.json
- core/file-locking/src/__tests__/lock.spec.ts
- core/readme/.prettierrc
- core/readme/package.json
- core/streams/.eslintrc.json
- core/streams/package.json
- tools/babel-preset/.eslintrc.json
- tools/babel-preset/package.json
- tools/eslint-config/package.json
- tools/eslint-plugin-verdaccio/package.json
**Scope:** ci
*  There is a related issue? **No**
**Description:** We want to pass tests in all available environments to ensure that everything can work as expected in every platform. Here we add Azure Pipelines to test the execution in Windows, Linux (Ubuntu) and MacOs. 
Also, there are some fixes necessary to work in Windows correctly
> ci: add Azure Pipelines 

- .devcontainer/devcontainer.json
**Scope:** all
*  There is a related issue? **No**
**Description:** Create a development environment using VSCode Remote Development tools. This will be improved with new settings and tools (e.g, we could have a Verdaccio instance running inside the container to make some things)
> chore: create a VSCode Remote Development environment

- core/types/index.d.ts
- plugins/auth-memory/test/index.spec.ts
- plugins/htpasswd/src/utils.ts
- plugins/local-storage/src/local-database.ts
**Scope:** all
Remove `$FlowFixMe` as comment, legacy from Flow
> refactor: remove FlowFixMe comment

- .circleci/config.yml
- package.json
**Type:** ci
**Scope:** all
*  There is a related issue? **Part of #13**
**Description:** Test if publish works correctly, publishing a canary version into an in memory registry
> ci: publish every commit in a temporal in-memory registry

- core/readme/package.json
- yarn.lock
High severity vulnerability found in dompurify
Description: Cross-site Scripting (XSS)
Info: https://snyk.io/vuln/SNYK-JS-DOMPURIFY-468981
Introduced through: @verdaccio/readme@8.1.0
From: @verdaccio/readme@8.1.0 > dompurify@1.0.11
> fix(security): Cross-site Scripting (XSS) for readme

- .circleci/config.yml
**Type:** ci
**Scope:** CircleCI
*  Unit or Functional tests are included in the PR No
**Description:** Update syntax to 2.1 and use new executors and commands section instead of aliases
> ci(circleci): migrate to CircleCI 2.1 syntax

- core/readme/jestEnvironment.js
- core/streams/jestEnvironment.js
- plugins/active-directory/jestEnvironment.js
- plugins/audit/jestEnvironment.js
- plugins/auth-memory/jestEnvironment.js
- plugins/aws-s3-storage/jestEnvironment.js
- plugins/google-cloud/jestEnvironment.js
- plugins/htpasswd/jestEnvironment.js
- plugins/htpasswd/tests/htpasswd.test.ts
- plugins/local-storage/jestEnvironment.js
- plugins/memory/jestEnvironment.js
> chore: upgrade require.requireActual -> jest.requireActual calls

- core/types/index.d.ts
**Type:**
typescript
**Scope:**
types
Adds a bit more validation for auth callbacks.
See https://verdaccio.org/docs/en/dev-plugins#callback for reference.
> Improve auth callback TS types

- core/types/index.d.ts
**Scope:** types
Add better types due 
https://github.com/verdaccio/generator-verdaccio-plugin/pull/18
> fix: add new types for local storage

- core/types/index.d.ts
- plugins/aws-s3-storage/src/s3PackageManager.ts
- plugins/google-cloud/src/storage.ts
- plugins/memory/src/memory-handler.ts
**Type:** fix
**Scope:** types
Improve and fix types for `ILocalPackageManager`
https://github.com/verdaccio/generator-verdaccio-plugin/pull/18
> fix: add types for storage handler

- core/file-locking/src/__tests__/lock.spec.ts
- plugins/aws-s3-storage/src/s3PackageManager.ts
- plugins/htpasswd/src/utils.ts
- tools/eslint-config/rules/prettier.js
**Type:** feat
**Scope:** eslint
*  Unit or Functional tests are included in the PR No
this is disabled by prettier default config and we want it enabled it
I notice that https://github.com/verdaccio/monorepo/pull/289 allows curly and our config should forbid such practice.
> feat: enable eslint curly

- core/commons-api/package.json
- core/file-locking/package.json
- core/readme/package.json
- core/streams/package.json
- core/types/package.json
- plugins/active-directory/package.json
- plugins/audit/package.json
- plugins/auth-memory/package.json
- plugins/aws-s3-storage/package.json
- plugins/google-cloud/package.json
- plugins/htpasswd/package.json
- plugins/local-storage/package.json
- plugins/memory/package.json
- tools/babel-preset/package.json
- tools/eslint-config/package.json
- tools/eslint-plugin-verdaccio/package.json
- tools/testing-utilities/package.json
**Type:** build
**Scope:**
Add funding info to all packages.
> build: add funding links to all packages

- plugins/local-storage/src/local-database.ts
**Type:**
bugfix
**Scope:**
local-storage
*  There is a related issue? Yes
*  Unit or Functional tests are included in the PR: No
bunyan already sanitizes objects and prevents circular reference exceptions.
Resolves https://github.com/verdaccio/verdaccio/issues/1639
> fix: prevent circular structure exception

- plugins/aws-s3-storage/README.md
- plugins/aws-s3-storage/src/index.ts
- plugins/aws-s3-storage/src/setConfigValue.ts
- plugins/aws-s3-storage/tests/setConfigValue.test.ts
**Type:** Feature
**Scope:** `aws-s3-storage`
Resolves #314
Add support for environment variables when reading the config values.
> feat(verdaccio-aws-s3-storage): supporting environment variables

- plugins/aws-s3-storage/.gitignore
- plugins/aws-s3-storage/Dockerfile
- plugins/aws-s3-storage/README.md
- plugins/aws-s3-storage/conf/config.yaml
- plugins/aws-s3-storage/src/index.ts
- plugins/aws-s3-storage/src/s3PackageManager.ts
**Scope:** aws-s3-storage
*  There is a related issue? no
*  Unit or Functional tests are included in the PR 
Improve Docker testing, was a bit flaky and hard to make it run, furthermore reduce the noise on logging (this will require a new PR) but for now is good enough to make it usable.
> refactor(verdaccio-aws-s3-storage): improve docker testing

- core/types/index.d.ts
relates to: https://github.com/verdaccio/verdaccio/pull/1687
> feat: adding tag type for auth plugins

- core/commons-api/test/errors.spec.ts
- package.json
- tools/babel-preset/package.json
- tools/eslint-config/package.json
- yarn.lock
**Type:** deps
**Scope:** all
Update Typescript to 3.8
https://devblogs.microsoft.com/typescript/announcing-typescript-3-8/
> fix: update typescript@3.8.2

- plugins/memory/.babelrc
- plugins/memory/jest.config.js
- plugins/memory/package.json
- plugins/memory/src/local-memory.ts
- plugins/memory/src/memory-handler.ts
- plugins/memory/test/memory.spec.ts
- plugins/memory/test/partials/config.ts
**Scope:** memory
* fix warnings
> refactor: fix lint warnings

- core/readme/package.json
- yarn.lock
**Type:** security
**Scope:** readme
More about this issue
> fix: update jsdom@16.2.1

- core/types/index.d.ts
See https://github.com/verdaccio/verdaccio/pull/1787
> Feature: Custom favicon

- .github/workflows/ci.yml
- plugins/memory/src/local-memory.ts
- plugins/memory/src/memory-handler.ts
- plugins/memory/src/utils.ts
- plugins/memory/test/local-memory.spec.ts
- plugins/memory/test/memory.spec.ts
**Type:** bug
**Scope:** plugin
- Fix race on fail on save package
- Refactor test ( add error use cases)
- Improve loggin
> fix(verdaccio-memory): race condition on save a package

- core/types/index.d.ts
**Type:** enhancement
**Scope:** core/types
this is the types for https://github.com/verdaccio/verdaccio/pull/1853. Please take a look!
> types for https config

- core/types/index.d.ts
https://github.com/verdaccio/verdaccio/blob/master/src/lib/auth.ts#L264
https://github.com/verdaccio/verdaccio/blob/master/src/lib/auth.ts#L114
**Type:** bug
**Scope:** typings
> Fix incorrect AuthAccessCallback and AuthCallback

- core/readme/package.json
- plugins/audit/package.json
- yarn.lock
**Type:** security
**Scope:** readme
* Same as https://github.com/verdaccio/monorepo/pull/377 https://snyk.io/vuln/SNYK-JS-MARKED-584281
* Update `request` for audit
> fix: update marked security vulnerability

- plugins/audit/README.md
- plugins/audit/package.json
- plugins/audit/src/audit.ts
- plugins/audit/tests/audit.spec.ts
- plugins/audit/tests/partial/webapp.ts
- yarn.lock
**Scope:** audit
Replace `request` by `node-fetch`
We have to do this all over the place :) this is the first try with something small.
> feat: replace request by node-fetch

- .github/workflows/ci.yml
- core/readme/package.json
- plugins/local-storage/package.json
- yarn.lock
> fix: update dependencies

- .github/workflows/ci.yml
- package.json
- plugins/local-storage/package.json
- plugins/local-storage/src/local-database.ts
- plugins/local-storage/src/local-fs.ts
- plugins/local-storage/src/pkg-utils.ts
- plugins/local-storage/src/token.ts
- plugins/local-storage/tests/__fixtures__/pkg.js
- plugins/local-storage/tests/__fixtures__/readme-test/package.json
- plugins/local-storage/tests/__mocks__/Config.ts
- plugins/local-storage/tests/local-database.test.ts
- plugins/local-storage/tests/token.test.ts
- yarn.lock
- Same as here https://github.com/verdaccio/verdaccio/pull/2043
- remove Node 8, 10 from build
-  update major mkdirp
> feat!: lowdb over level for token

- plugins/local-storage/src/local-database.ts
- plugins/local-storage/tests/__mocks__/Config.ts
> fix: restore self_path variable

- plugins/local-storage/package.json
- plugins/local-storage/src/local-database.ts
- yarn.lock
Add warning to rename database name
> fix: add warning database name

- plugins/audit/package.json
- plugins/audit/src/audit.ts
- pnpm-lock.yaml
fix https://github.com/verdaccio/verdaccio/issues/2308
> feat: add npm7 support to npm audit plugin

- .changeset/witty-plants-teach.md
- core/types/index.d.ts
**Type:** feat
**Scope:** types
- Add missing types for server 
- Convert user agent to boolean
- Add RateLimit
> feat: add rate limit and convert user agent type to boolean

- .changeset/tiny-rocks-grin.md
- core/readme/package.json
- pnpm-lock.yaml
rollback jsdom ref https://github.com/verdaccio/monorepo/pull/541
> fix: downgrade jsdom

- .changeset/wet-jeans-share.md
- core/types/index.d.ts
**Type:**
**Scope:**
Aling with v6
> feat: update configuration types

- .changeset/cold-rockets-explain.md
- plugins/htpasswd/src/htpasswd.ts
- plugins/htpasswd/src/utils.ts
- plugins/htpasswd/tests/htpasswd.test.ts
- plugins/htpasswd/tests/utils.test.ts
> fix: eliminating all synchronous calls to bcrypt library

- .changeset/clean-mirrors-explode.md
- core/types/src/configuration.ts
[Related to discussion Rate limiting when behind a proxy or load balancer](https://github.com/verdaccio/verdaccio/discussions/3269#discussioncomment-3206509)
> Add `server.trustProxy` configuration type

- .changeset/fifty-eggs-know.md
- core/types/src/manifest.ts
Implement https://github.com/verdaccio/verdaccio/pull/3322 on v5.x
> feat: add abbreviated versions support

- core/types/src/manifest.ts
**Type:**
**Scope:**
*  There is a related issue? https://github.com/verdaccio/verdaccio/pull/3347
> feat(types): add missing fields to the Version object

- .changeset/thirty-kangaroos-dress.md
- plugins/htpasswd/package.json
- plugins/htpasswd/src/htpasswd.ts
- pnpm-lock.yaml
**Type:** fix
**Scope:** plugin/auth
- Add extra logging on startup
> fix: add logging to plugin startup
